sudo: required
services:
  - docker

before_install:
  - docker build -t geckobjj/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true geckobjj/react-test npm test

after_success:
  - docker build -t geckobjj/fib-client ./client
  - docker build -t geckobjj/fib-nginx ./nginx
  - docker build -t geckobjj/fib-server ./server
  - docker build -t geckobjj/fib-worker ./worker
  #Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take these images and push them to docker hub
  - docker push geckobjj/fib-client
  - docker push geckobjj/fib-nginx
  - docker push geckobjj/fib-server
  - docker push geckobjj/fib-worker

  deploy:
    provider: elasticbeanstalk
    region: us-east-1
    app: fibonacci-machine
    env: Fibonaccimachine-env
    bucket_name: elasticbeanstalk-us-east-1-148228404143
    bucket_path: docker-multi
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY